### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Jobians** [nutgram/nutgram#226]
### Is your feature request related to a problem? Please describe.

Please can you give example bot code without using composer

**Comment by SergiX44** [comment]
I would like to encourage good practices, so no, the only way to use it is to manually require the every class you need to use.
But c'mon its 2022, if you are trying to use PHP third-party libraries without composer is like using python without pip, pipenv or conda, or node without npm, yarn, etc. 
Unless you are on a very legacy project (which I dont think since nutgram supports >=php8), you should use composer.
