### ISSUE TITLE
[BUG] Bug in onCallbackQueryData

### ISSUE THREAD

**Issue by devdasher** [nutgram/nutgram#601]
### Nutgram version

4.10.0

### PHP version

8.2.4

### Framework

No Framework

### Cache driver

FilesystemAdapter

### Describe the bug

There is a bug similar to #583 in `onCallbackQueryData` method !

My code (line 62 & 63):

![photo_2023-10-13_21-44-34](https://github.com/nutgram/nutgram/assets/78247242/113377a1-c842-4380-ac76-974167032e09)

When i click on a button with Callback Data `sett/posts/15/delete` instead of executing the code on line 63 it executes what is on 62

### Expected behavior

The existing pattern should be checked exactly and the appropriate Callable should be executed.

**Comment by Lukasss93** [comment]
It's not a bug. Like any routing system, the {id} parameter captures any type of input. To address this "issue," you can:

- Move line 63 above line 62 so that the more specific handler is registered first.
```php
$bot->onCallbackQueryData('set/value/{id}/delete', $action);
$bot->onCallbackQueryData('set/value/{id}', $action);
```
- Add a constraint using the "where" method and the $ character:
```php
$bot->onCallbackQueryData('set/value/{id}$', $action)->where('id', '\d+');
$bot->onCallbackQueryData('set/value/{id}/delete', $action);
```

This way, the routing system will correctly match the more specific route when the input is "set/value/{id}/delete."
