### ISSUE TITLE
[BUG] Incompatible Hydrator Type in Configuration and Nutgram Classes

### ISSUE THREAD

**Issue by joolab** [nutgram/nutgram#661]
### Nutgram version

4.15

### PHP version

8.2

### Framework

No Framework

### Cache driver

All

### OS

All

### Describe the bug

I encountered an issue in the library related to the `$hydrator` field within the `Configuration` class, which is specified to accept types `HydratorInterface|string`. The problem arises when trying to assign an instance or a class that implements `HydratorInterface` to this field. The operation fails due to a type incompatibility issue with the `$hydrator` field in the `Nutgram` class, which is strictly typed to `Hydrator`. This discrepancy makes it impossible to pass a custom hydrator through the configuration, whether it is of type `Hydrator` or `HydratorInterface`.

### To Reproduce

1. Create a class that implements `HydratorInterface`.
2. Attempt to pass an instance of this class (or the class itself if using its name as a string) to the `Configuration` class's `$hydrator` field.
3. Observe the error indicating a type mismatch with the `Nutgram` class's `$hydrator` field.

### Expected behavior

I would expect that any class or instance that implements `HydratorInterface` should be assignable to the `$hydrator` field in the `Configuration` class and be compatible with the `Nutgram` class's expectations for the hydrator.

### Additional context

Possible Solution:
Adjusting the type declaration for the `$hydrator` field in both the `Configuration` and `Nutgram` classes to ensure compatibility with `HydratorInterface` could resolve the issue. This would enable the flexibility to pass custom hydrators that implement this interface.

**Comment by sergix44** [comment]
The Hydrator interface is something that will be probably removed in the future, because it was introduced back in 3.0 when transitioning from netresearch/json-mapper to our own fork of another hydrator, later extended and improved, so the integration between the nutgram and its hydrator is much more tigher than in the beginning.
Those are the changes/features needed that led to that tigher integration:
- Flexible enum casting, needed when telegram changes things that are not in our control (eg. https://github.com/nutgram/nutgram/blob/master/src/Telegram/Types/Inline/InlineQueryResultLocation.php#L21)
- abstract type resolvers: solve the correct class to instantiate based on the input json object (eg. https://github.com/nutgram/nutgram/blob/master/src/Telegram/Types/Chat/ChatMember.php#L21)
- dependecy injection: ability to inject services inside the DTOs that are instantiated (eg. https://github.com/nutgram/nutgram/blob/master/src/Telegram/Types/BaseType.php#L29)
- explicit types for arrays (eg. https://github.com/nutgram/nutgram/blob/master/src/Telegram/Types/Message/Message.php#L224)

And there is probably more. As you can see many of those features are declared via attributes, which are going to be completely ignored if you pick any other hydrator
